# Generated by Django 5.1.6 on 2025-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bearertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearertoken',
            name='token',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
