# Generated by Django 5.1 on 2024-12-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeDataLayerYearStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.IntegerField()),
                ('data_layer', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['shape_id', 'data_layer', 'year'], name='dashboard_s_shape_i_0c93d9_idx')],
                'unique_together': {('shape_id', 'data_layer', 'year')},
            },
        ),
    ]
