# Generated by Django 5.0.1 on 2024-04-10 14:44

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Datalayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_included', models.DateField(blank=True, null=True)),
                ('operation', models.CharField(blank=True, max_length=255)),
                ('database_unit', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(blank=True, max_length=255)),
                ('format_description', models.TextField(blank=True)),
                ('format_unit', models.CharField(blank=True, max_length=255)),
                ('spatial_details', models.CharField(blank=True, max_length=255)),
                ('spatial_coverage', models.CharField(blank=True, max_length=255)),
                ('temporal_details', models.CharField(blank=True, max_length=255)),
                ('temporal_coverage', models.CharField(blank=True, max_length=255)),
                ('source', models.TextField(blank=True)),
                ('source_link', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=255)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('date_published', models.TextField(blank=True)),
                ('date_last_accessed', models.DateField(blank=True, null=True)),
                ('citation', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='datalayers', to='datalayers.category')),
                ('related_to', models.ManyToManyField(blank=True, to='datalayers.datalayer')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='DatalayerLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Informational'), ('notice', 'Notice'), ('warning', 'Warning'), ('err', 'Error'), ('crit', 'Critical'), ('alert', 'Alert'), ('emerg', 'Emergency')], max_length=10)),
                ('message', models.TextField()),
                ('context', models.JSONField(default=list)),
                ('datalayer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='logentries', to='datalayers.datalayer')),
            ],
        ),
        migrations.CreateModel(
            name='DatalayerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pid_type', models.CharField(choices=[('DOI', 'DOI'), ('ROR', 'ROR'), ('ORCID', 'ORCID')], default='DOI', max_length=255)),
                ('pid', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('datacite', models.JSONField(blank=True, editable=False, null=True)),
                ('datacite_fetched_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('datalayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sources', to='datalayers.datalayer')),
            ],
        ),
    ]
