# Generated by Django 5.0.1 on 2024-02-14 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Datalayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('necessity', models.CharField(blank=True, max_length=255)),
                ('original_unit', models.CharField(blank=True, max_length=255)),
                ('operation', models.CharField(blank=True, max_length=255)),
                ('database_unit', models.CharField(blank=True, max_length=255)),
                ('details_spatial', models.CharField(blank=True, max_length=255)),
                ('details_temporal', models.CharField(blank=True, max_length=255)),
                ('timeframe', models.CharField(blank=True, max_length=255)),
                ('related_sources', models.CharField(blank=True, max_length=255)),
                ('creator', models.CharField(blank=True, max_length=255)),
                ('included_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(blank=True, max_length=255)),
                ('identifier', models.CharField(blank=True, max_length=255)),
                ('source', models.TextField(blank=True)),
                ('source_link', models.TextField(blank=True)),
                ('citation', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=255)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('coverage', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='datalayers', to='datalayers.category')),
            ],
        ),
    ]
