# Generated by Django 5.0.7 on 2024-07-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalayersource',
            name='datalayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='datalayers.datalayer'),
        ),
    ]
