# Generated by Django 5.1.3 on 2024-11-25 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0003_category_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalayerlogentry',
            name='datalayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logentries', to='datalayers.datalayer'),
        ),
    ]
