# Generated by Django 5.1.3 on 2025-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0004_alter_datalayerlogentry_datalayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalayer',
            name='description',
            field=models.TextField(blank=True, help_text='You can use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> for text formatting, including tables and footnotes.'),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='key',
            field=models.SlugField(help_text='Unique key identifying this Data Layer, use only <code>a-z</code>, <code>0-9</code> and <code>_</code>. Follow the convention of <code>&lt;source&gt;_&lt;parameter&gt;</code>.', max_length=255, unique=True),
        ),
    ]
