# Generated by Django 5.1.5 on 2025-01-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0005_alter_datalayer_description_alter_datalayer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='caveats',
            field=models.TextField(blank=True, help_text='Describe known issues and caveats of the Data Layer. You can use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> for text formatting, including tables and footnotes.', null=True),
        ),
        migrations.AddField(
            model_name='datalayer',
            name='data_type',
            field=models.CharField(choices=[('primary', 'Primary data'), ('secondary', 'Secondary data')], default='secondary', help_text='Highlight if this Data Layer uses primary, i.e., you own data, or if it uses secondary data from someone else.', max_length=10, verbose_name='Data type'),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the Data Layer. You can use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> for text formatting, including tables and footnotes.', null=True),
        ),
    ]
