# Generated by Django 5.1.5 on 2025-01-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0006_datalayer_caveats_datalayer_data_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalayer',
            name='database_unit',
            field=models.CharField(blank=True, help_text='Unit of the harmonized values of this Data Layer, i.e., °C, mm, entities, …', max_length=255),
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='operation',
            field=models.TextField(blank=True, help_text='Describe the operation performed to harmonize the raw data, i.e., mean, sum, …'),
        ),
    ]
