# Generated by Django 5.1.5 on 2025-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0008_sourcemetadata_delete_datalayersource'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemetadata',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='date_published',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='license',
            field=models.CharField(blank=True, help_text='SPDX identifier of the given license if available', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='pid',
            field=models.CharField(blank=True, help_text='Fetching DOI data will overwrite name, license and DataCite fields.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='pid_type',
            field=models.CharField(blank=True, choices=[('DOI', 'DOI'), ('ROR', 'ROR'), ('ORCID', 'ORCID')], default='', max_length=255),
        ),
    ]
