# Generated by Django 5.1.5 on 2025-02-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0009_sourcemetadata_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcemetadata',
            options={'ordering': ('datalayer', 'position')},
        ),
        migrations.RemoveField(
            model_name='sourcemetadata',
            name='source',
        ),
        migrations.RemoveField(
            model_name='sourcemetadata',
            name='source_link',
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='format',
            field=models.CharField(blank=True, help_text='File type of the source, preferable it\'s MIME type, see <a target="_blank" href="https://www.iana.org/assignments/media-types/media-types.xhtml">list of available types</a>', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='language',
            field=models.CharField(blank=True, help_text='ISO 639 language code.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='pid_type',
            field=models.CharField(blank=True, choices=[('URL', 'URL'), ('DOI', 'DOI'), ('ROR', 'ROR'), ('ORCID', 'ORCID')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Field to order the meta data entries, if 0 will appended to at the end.'),
        ),
    ]
