# Generated by Django 5.1.5 on 2025-02-19 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0011_sourcemetadata_format_api_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalayer',
            options={'ordering': ('key', 'name')},
        ),
        migrations.RenameField(
            model_name='sourcemetadata',
            old_name='source_type',
            new_name='metadata_type',
        ),
        migrations.AlterField(
            model_name='datalayer',
            name='date_included',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='date_published',
            field=models.CharField(blank=True, help_text='Year of publication in yyyy format.'),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='format_api',
            field=models.BooleanField(default=False, help_text='Check, if the source data are dynamically requested from an API. Use format field to specify the format of the data returned by the API, i.e., JSON.', verbose_name='Source is an API'),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='language',
            field=models.CharField(blank=True, help_text='Prefer ISO 639-3 language code (3 letters), see <a target="_blank" href="https://iso639-3.sil.org/code_tables/639/data">SIL for full list</a>. Other ISO 639 codes are allowed as well.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='spatial_coverage',
            field=models.CharField(blank=True, help_text='What extend of the world dose the source cover, i.e., <code>global</code>, country code (ISO 3611-1 alpha3 preferred, separate by , in case of multiple), degrees', max_length=255),
        ),
    ]
