# Generated by Django 5.1.5 on 2025-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0012_alter_datalayer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemetadata',
            name='source_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sourcemetadata',
            name='source_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='metadata_type',
            field=models.CharField(choices=[('data', 'Data source'), ('information', 'Further information')], default='data', help_text='Differentiate if this an actual data source of the Data Layer or further information.', max_length=20, verbose_name='Metadata type'),
        ),
    ]
