# Generated by Django 5.1.6 on 2025-02-24 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0013_sourcemetadata_source_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemetadata',
            name='spatial_coverage_east_bound_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Easternmost coordinate (Longitude, -180 to 180).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='sourcemetadata',
            name='spatial_coverage_north_bound_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Northernmost coordinate (Latitude, -90 to 90).', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='sourcemetadata',
            name='spatial_coverage_south_bound_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Southernmost coordinate (Latitude, -90 to 90).', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='sourcemetadata',
            name='spatial_coverage_west_bound_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Westernmost coordinate (Longitude, -180 to 180).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
