# Generated by Django 5.1.6 on 2025-02-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0014_sourcemetadata_spatial_coverage_east_bound_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcemetadata',
            name='spatial_epsg',
            field=models.PositiveIntegerField(blank=True, help_text='EPSG ID of the data source.', null=True),
        ),
        migrations.AddField(
            model_name='sourcemetadata',
            name='spatial_resolution_x_distance',
            field=models.FloatField(blank=True, help_text='For raster data, distance value', null=True),
        ),
        migrations.AddField(
            model_name='sourcemetadata',
            name='spatial_resolution_x_unit',
            field=models.CharField(blank=True, choices=[('meters', 'Meters'), ('kilometers', 'Kilometers'), ('degrees', 'Degrees')], help_text='For raster data, distance unit', null=True),
        ),
        migrations.AddField(
            model_name='sourcemetadata',
            name='spatial_resolution_y_distance',
            field=models.FloatField(blank=True, help_text='For raster data, distance value', null=True),
        ),
        migrations.AddField(
            model_name='sourcemetadata',
            name='spatial_resolution_y_unit',
            field=models.CharField(blank=True, choices=[('meters', 'Meters'), ('kilometers', 'Kilometers'), ('degrees', 'Degrees')], help_text='For raster data, distance unit', null=True),
        ),
    ]
