# Generated by Django 5.1.6 on 2025-03-03 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0015_sourcemetadata_spatial_epsg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemetadata',
            name='spatial_coverage_east_bound_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Easternmost coordinate (Longitude, -180 to 180).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='[Raster] East (→) bound'),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='spatial_coverage_north_bound_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Northernmost coordinate (Latitude, -90 to 90).', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='[Raster] North (↑) bound'),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='spatial_coverage_south_bound_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Southernmost coordinate (Latitude, -90 to 90).', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='[Raster] South (↓) bound'),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='spatial_coverage_west_bound_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Westernmost coordinate (Longitude, -180 to 180).', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='[Raster] West (←) bound'),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='spatial_epsg',
            field=models.PositiveIntegerField(blank=True, help_text='EPSG ID of the data source.', null=True, verbose_name='EPSG-Code'),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='spatial_resolution',
            field=models.CharField(blank=True, help_text='Resolution of the source, i.e., x km for raster data, <code>coordinates</code> for Points, administrative unit/region for vector files.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='spatial_resolution_x_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='[Raster] cell width value'),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='spatial_resolution_x_unit',
            field=models.CharField(blank=True, choices=[('meters', 'Meters'), ('kilometers', 'Kilometers'), ('degrees', 'Degrees')], null=True, verbose_name='[Raster] cell width unit'),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='spatial_resolution_y_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='[Raster] height value'),
        ),
        migrations.AlterField(
            model_name='sourcemetadata',
            name='spatial_resolution_y_unit',
            field=models.CharField(blank=True, choices=[('meters', 'Meters'), ('kilometers', 'Kilometers'), ('degrees', 'Degrees')], null=True, verbose_name='[Raster] cell height unit'),
        ),
    ]
