# Generated by Django 5.2.3 on 2025-11-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0016_alter_sourcemetadata_spatial_coverage_east_bound_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcemetadata',
            name='pid_type',
            field=models.CharField(blank=True, choices=[('DOI', 'DOI'), ('ROR', 'ROR'), ('ORCID', 'ORCID'), ('URL', 'URL'), ('URN', 'URN')], default='', help_text='In case of URL put the URL into the PID field.', max_length=255, verbose_name='PID type'),
        ),
    ]
