# Generated by Django 5.2.10 on 2026-01-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0017_alter_sourcemetadata_pid_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
