# Generated by Django 5.2.12 on 2026-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0018_category_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='data_access',
            field=models.BooleanField(default=True, help_text='If unchecked access to visualizations, data download and API access for this layer will be restricted to staff and super users.'),
        ),
        migrations.AddField(
            model_name='datalayer',
            name='visibility',
            field=models.CharField(choices=[('listed', 'Listed'), ('restricted', 'Restricted'), ('private', 'Private')], default='listed', max_length=20),
        ),
    ]
