# Generated by Django 5.2.14 on 2026-06-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0019_datalayer_data_access_datalayer_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalayer',
            name='data_access',
            field=models.BooleanField(default=True, help_text='If unchecked access to visualizations, data download and API access for the data of this layer will be restricted to staff and super users.'),
        ),
    ]
