# Generated by Django 5.1.5 on 2025-01-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0002_shape_admin_shape_attribution_html_shape_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='attribution_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='attribution_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='attribution_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='license',
            field=models.TextField(blank=True, help_text='SPDX identifier of the license if available.', null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
