# Generated by Django 5.1.5 on 2025-01-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0003_alter_shape_attribution_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='admin',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
