# Generated by Django 5.1.5 on 2025-01-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0004_alter_shape_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
